
export const ortho2dVert = `#version 300 es
precision highp float;
layout(location=0)in vec2 _v;layout(location=1)in vec3 _u;layout(location=2)in vec3 _c;layout(location=3)in vec4 _l;out vec3 _w;out vec4 _r;void main(){_w=_u;_r=_l;float v=cos(_c.z),n=sin(_c.z);vec2 l=mat2(v,n,-n,v)*_v+_c.xy;gl_Position=vec4((l/vec2(600.,800.)-.5)*2.,0.,1.);}`;
export const screenVert = `#version 300 es
precision highp float;
layout(location=0)in vec2 _v;out vec3 _w;out vec4 _r;void main(){_w=vec3(_v.xy*.5+.5,0);gl_Position=vec4(_v,0.,1.);_r=vec4(1);}`;
export const sdfScreenVert = `#version 300 es
precision highp float;
layout(location=0)in vec2 _v;out vec2 _u;out vec3 _ro,_rd;uniform mat4 _mv,_mp;void main(){_u=vec2(_v.x,_v.y);gl_Position=vec4(_v,0.,1.);mat4 v=inverse(_mp*_mv);vec4 n=v*vec4(_u,-1,1);_ro=n.xyz/n.w;vec4 m=v*vec4(_u,1,1);_rd=normalize(m.xyz/m.w-_ro);}`;
export const sdfSpriteVert = `#version 300 es
precision highp float;
layout(location=0)in vec2 _q;uniform mat4 _mv,_mp;layout(std140) uniform _b{vec4 settings;vec4 data[200];vec4 posScale[200];vec4 qRotation[200];};out vec3 _ic,_ro,_rd;out vec4 _sd;out float _ss;out mat3 _vr;mat3 v(vec4 v){vec2 m=vec2(1.,-1.);return mat3(mat4(v.wzyx*m.xxyx,v.zwxy*m.yxxx,v.yxwz*m.xyxx,v.xyzw*m.yyyx)*mat4(v.wzyx*m.xxyy,v.zwxy*m.yxxy,v.yxwz*m.xyxy,v.xyzw*m.xxxx));}vec3 v(mat4 v,vec3 m){vec4 c=v*vec4(m,1);return(c/c.w).xyz;}void main(){_ic=(_mv*vec4(posScale[gl_InstanceID].xyz,1)).xyz;_ss=posScale[gl_InstanceID].w;_sd=data[gl_InstanceID];_vr=inverse(mat3(_mv)*v(qRotation[gl_InstanceID]));vec3 m=v(_mp,_ic),x=v(_mp,_ic.xyz+vec3(_q,1)*_ss),c=v(_mp,_ic.xyz+vec3(_q,-1)*_ss);if(abs(c.x-m.x)>abs(x.x-m.x))x.x=c.x;if(abs(c.y-m.y)>abs(x.y-m.y))x.y=c.y;gl_Position=vec4(x,1);mat4 y=inverse(_mp);_ro=v(y,x);vec4 s=inverse(_mp)*vec4(gl_Position.xy,1,1);_rd=normalize(s.xyz/s.w-_ro.xyz);}`;
export const finalSdfFrag = `#version 300 es
precision highp float;
in vec2 uv;out vec4 _f;uniform float _ut;uniform highp sampler3D _t,_m;layout(std140) uniform _b{vec4 settings;vec4 data[200];vec4 posScale[200];vec4 qRotation[200];};vec2 v(in vec3 v,float i){vec3 f=vec3(.5,1.,1.)*(v+1.)*.5+vec3(float(i)*.5,0.,0.);return vec2(texture(_t,f).x,texture(_m,f).x);}vec2 v(in vec3 i,float f,in vec2 x){float c=length(i),t=c-1.;if(x.x<t)return x;if(c>1.){vec2 u=v(i/c,f);return u+vec2(t,0);}return v(i,f);}vec2 v(in vec3 i,float f,vec4 c,vec2 x){vec2 u=v((i-c.xyz)/c.w,f,x);return u*vec2(c.w,1);}vec2 f(vec2 v,vec2 x){return v.x<x.x?v:x;}vec2 f(vec3 i){vec2 x=vec2(i.z,0);int u=int(settings.x);for(int r=0;r<u;++r)x=f(x,v(i,data[r].x,posScale[r],x));return x-vec2(.03,0);}float f(in vec3 i,in vec3 v,float x,float u,float c){float r=1.,y=x;for(int s=0;s<20&&y<u;s++){float t=f(i+y*v).x;r=min(r,t/(c*y));y+=clamp(t,.005,.5);if(r<-1.||y>u)break;}r=max(r,-1.);return.25*(1.+r)*(1.+r)*(2.-r)>.5?1.:0.;}vec3 v(in vec3 i){vec2 v=vec2(1.,-1.)*.5773;const float x=5e-4;return normalize(v.xyy*f(i+v.xyy*x).x+v.yyx*f(i+v.yyx*x).x+v.yxy*f(i+v.yxy*x).x+v.xxx*f(i+v.xxx*x).x);}float f(vec3 v,vec3 x,out float i){float u=0.;for(int r=0;r<100;++r){vec3 c=v+x*u;vec2 s=f(c);if(u>16.||abs(s.x)<.001){i=s.y;break;}u+=s.x;}return u;}float i(in vec3 i,in vec3 v){return dot(i,v);}void main(){vec3 x=vec3(0.);float u=5.,r=_ut;vec3 c=vec3(cos(r)*u,sin(r)*u,u),t=normalize(-c),y=normalize(cross(t,vec3(0.,0.,1.))),s=normalize(cross(t,y));vec2 n=4.5*uv;vec3 m=c+n.x*y+n.y*s;for(int d=0;d<1;d++)for(int o=0;o<1;o++){float z,p=f(m,t,z);vec3 l=vec3(0.);if(p<16.){vec3 w=m+p*t,e=v(w),a=vec3(.7,.6,.4);float h=f(w,a,.1,6.,.1),k=h*clamp(i(e,a),0.,1.),g=.5+.5*i(e,vec3(0.,.8,.6));vec3 b=vec3(.2,.3,.4);if(z==1.)b=vec3(0.,0.,1.);if(z==2.)b=vec3(1.,0.,0.);l=b*g+vec3(.8,.7,.5)*k;}x+=l;}x/=float(1);_f=vec4(x,0.);}`;
export const sdfFloorFrag = `#version 300 es
precision highp float;
out vec4 _f;in vec2 _u;in vec3 _ro,_rd;uniform mat4 _mv,_mp;uniform vec4 _d;uniform vec3 _ld,_lc,_la,_lb;uniform highp sampler3D _t,_w;float v(vec2 v,vec2 y){vec2 d=abs(v)-y;return length(max(d,0.))+min(max(d.x,d.y),0.);}float v(vec2 v){return 0.;}float x(vec3 v,vec2 y){vec2 d=texture(_w,fract(y*1242.345).xyy).xy;float f=mix(.2,.6,d.x);return length(v)-f;}vec2 m(vec3 v,out vec2 f){v.y+=_d.y;f=v.xy;vec3 d=vec3(fract(f*.01),0);vec4 m=texture(_t,d);float t=.5+m.w*100.;vec2 y=vec2(v.z+t,0);return y;}float m(vec3 v,vec3 y,out float f,out vec2 d){float x=0.;for(int i=0;i<90;++i){vec3 t=v+y*x;vec2 h=m(t,d);if(x>350.||abs(h.x)<.01){f=h.y;break;}x+=h.x;}return x;}vec3 m(in vec3 v){float d=.001;vec2 f=vec2(1,-1),y;return normalize(f.xyy*m(v+f.xyy*d,y).x+f.yyx*m(v+f.yyx*d,y).x+f.yxy*m(v+f.yxy*d,y).x+f.xxx*m(v+f.xxx*d,y).x);}float m(in vec3 v,in vec3 d,float y,float x,float f){float i=1.,t=y;vec2 o;for(int r=0;r<256&&t<x;r++){float h=m(v+d*t,o).x;if(h<.001)return 0.;i=min(i,f*h/t);t+=h;}return i;}void main(){float d;vec2 y;float f=m(_ro,_rd,d,y);vec3 t=vec3(.1,0,.1);if(f>=350.){_f=vec4(t,1);gl_FragDepth=-1.;return;}vec3 i=_ro+f*_rd,o=m(i);float x=dot(o,_ld);vec3 r=max(0.,x)*_lc*m(i,_ld,.1,30.,.8);r+=max(0.,-x)*_lb;r+=_la;vec3 h=d==0.?vec3(.5,.25,.1):vec3(.1,.6,.1),u=r*h;u=mix(u,t,f/350.*(f/350.));if(_rd.z!=0.){vec3 l=_ro+_rd*-_ro.z/_rd.z;vec2 z=l.xy;float n=smoothstep(0.,1.5,v(z,_d.zw))*.75*texture(_t,vec3(z/10.+vec2(0,_d.y*.08),0)).w;u=mix(u,vec3(.6,.6,.65),n);}_f=vec4(u,1);vec4 l=_mp*_mv*vec4(i,1);gl_FragDepth=l.z/l.w*.5+.5;}`;
export const sdfSpriteFrag = `#version 300 es
precision highp float;
out vec4 _f;in vec3 _ic,_ro,_rd;in vec4 _sd;in float _ss;uniform highp sampler3D _t,_m;in mat3 _vr;uniform vec3 _ld,_lc,_la,_lb;uniform mat4 _mv,_mp;float v;vec3 i;vec2 f(in vec3 v){vec3 f=(v*.5+.5+i)/vec3(5.,5.,1.);return vec2(texture(_t,f).x,texture(_m,f).x);}vec2 m(in vec3 v){float m=length(v),i=m-1.;if(m>1.){vec2 x=f(v/m);return x+vec2(i,0);}return f(v);}vec2 e(vec3 v){vec2 i=m(_vr*(v-_ic)/_ss);i.x*=_ss;return i;}float e(vec3 m,vec3 x,out float f){float i=0.;for(int r=0;r<100;++r){vec3 n=m+x*i;vec2 d=e(n);if(i>v||abs(d.x)<.001){f=d.y;break;}i+=d.x;}return i;}vec3 x(vec3 v){const float f=.5/90.;const vec2 i=vec2(1,-1);return normalize(i.xyy*e(v+i.xyy*f).x+i.yyx*e(v+i.yyx*f).x+i.yxy*e(v+i.yxy*f).x+i.xxx*e(v+i.xxx*f).x);}const vec3 n[9]=vec3[9](vec3(0,0,0),vec3(1,0,1),vec3(0,.4,.15),vec3(.85,.7,.5),vec3(.9,0,0),vec3(1,1,.95),vec3(.94,.8,0),vec3(.1,.1,.1),vec3(.2,.4,.65));void main(){vec3 f=vec3(0.);v=_ss*2.1;i=vec3(_sd.xy,0);float m,y=e(_ro,_rd,m);if(y>=v)discard;vec3 d=_ro+y*_rd,t=x(d);float r=dot(t,_ld);vec3 s=max(0.,r)*_lc;s+=max(0.,-r)*_lb;s+=_la;int h=int(m)&15;vec3 p=n[h];if(m<2.)f=p;else f=p*s;f=mix(f,vec3(1),_sd.w);_f=vec4(f,1);vec4 l=_mp*vec4(0,0,d.z,1);gl_FragDepth=l.z/l.w*.5+.5;}`;
export const uvColorFrag = `#version 300 es
precision highp float;
out vec4 _f;in vec4 _r;uniform highp sampler2D _s;in vec3 _w;void main(){_f=texture(_s,_w.xy)*_r;}`;
