
import { DEBUG } from "./autogenerated";
import * as glEnum from "./webglEnums";

import { createSdf } from "./sdfBuilder";
import * as SdfBuilderOps from "./sdfBuilderOps";
import { raymarchImage } from "./sdfRaymarcher";
import { Vec3, mat4LookAt, vec3, zAxis, zeroVector } from "./juvec";
import { Pi, cos, min, saturate, sin } from "./aliasedFunctions";
import { sdfBakeToTexture } from "./sdfMapper";
import { bakeSdfs } from "./sdfSprites";
import * as SdfSpriteIndices from "./sdfSpriteIndices";
import { entities, gameInit, gameMainLoop } from "./game";
import { fillBufferWithRandomRange, fbmTexture } from "~noise";

import { titlescreenInit, titlescreenLoop } from "~titlescreen";
import { roadmapInit, roadmapLoop } from "~roadmap";

import { initMain } from "./main";
import { keyHandler, } from "./input";
import { initRenderer } from "./renderer";
import { audioCtx, initSound, loadSamples, samplesRendered } from "./audio";


window.addEventListener('DOMContentLoaded', () => {
    window.addEventListener('keydown', (event: KeyboardEvent) => {
        if (samplesRendered && !audioCtx) {
            initSound();
            loadSamples();
        }
        keyHandler(event, true);
    }, true);

    window.addEventListener('keyup', (event: KeyboardEvent) => {
        keyHandler(event, false);
    }, true);
    initRenderer().then(initMain);
});